// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

/**
 * CharsetInfo 表示 MySQL 支持的字符集及其默认排序规则。
 */
export class CharsetInfo {
    /**
     * Creates a new CharsetInfo instance.
     * @param {Partial<CharsetInfo>} [$$source = {}] - The source object to create the CharsetInfo.
     */
    constructor($$source = {}) {
        if (!("charset" in $$source)) {
            /**
             * 字符集名
             * @member
             * @type {string}
             */
            this["charset"] = "";
        }
        if (!("defaultCollation" in $$source)) {
            /**
             * 默认排序规则
             * @member
             * @type {string}
             */
            this["defaultCollation"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * 描述
             * @member
             * @type {string}
             */
            this["description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CharsetInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CharsetInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CharsetInfo(/** @type {Partial<CharsetInfo>} */($$parsedSource));
    }
}

/**
 * ColumnDef 是建表时的一列定义。
 */
export class ColumnDef {
    /**
     * Creates a new ColumnDef instance.
     * @param {Partial<ColumnDef>} [$$source = {}] - The source object to create the ColumnDef.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * 列名
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("dataType" in $$source)) {
            /**
             * 数据类型（如 "INT", "VARCHAR(255)"）
             * @member
             * @type {string}
             */
            this["dataType"] = "";
        }
        if (!("nullable" in $$source)) {
            /**
             * 是否可空
             * @member
             * @type {boolean}
             */
            this["nullable"] = false;
        }
        if (!("defaultValue" in $$source)) {
            /**
             * 默认值（空串表示无默认值）
             * @member
             * @type {string}
             */
            this["defaultValue"] = "";
        }
        if (!("autoIncrement" in $$source)) {
            /**
             * 是否自增
             * @member
             * @type {boolean}
             */
            this["autoIncrement"] = false;
        }
        if (!("unsigned" in $$source)) {
            /**
             * 是否无符号（数值类型）
             * @member
             * @type {boolean}
             */
            this["unsigned"] = false;
        }
        if (!("comment" in $$source)) {
            /**
             * 列注释
             * @member
             * @type {string}
             */
            this["comment"] = "";
        }
        if (!("isPrimaryKey" in $$source)) {
            /**
             * 是否主键
             * @member
             * @type {boolean}
             */
            this["isPrimaryKey"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ColumnDef instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ColumnDef}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ColumnDef(/** @type {Partial<ColumnDef>} */($$parsedSource));
    }
}

/**
 * ColumnInfo 描述查询结果中的一列元数据。
 */
export class ColumnInfo {
    /**
     * Creates a new ColumnInfo instance.
     * @param {Partial<ColumnInfo>} [$$source = {}] - The source object to create the ColumnInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * 列名
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * MySQL 类型字符串，如 "VARCHAR(255)", "INT"
             * @member
             * @type {string}
             */
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ColumnInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ColumnInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ColumnInfo(/** @type {Partial<ColumnInfo>} */($$parsedSource));
    }
}

/**
 * Connection 表示一个数据库连接配置。
 * SSHConfig 为非零值时自动通过 SSH 隧道连接远程数据库。
 */
export class Connection {
    /**
     * Creates a new Connection instance.
     * @param {Partial<Connection>} [$$source = {}] - The source object to create the Connection.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("groupId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["groupId"] = "";
        }
        if (!("host" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["username"] = "";
        }
        if (!("password" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["password"] = "";
        }
        if (!("database" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["database"] = "";
        }
        if (!("timezone" in $$source)) {
            /**
             * IANA 时区名（如 "Asia/Shanghai"），空值等价于 "Local"
             * @member
             * @type {string}
             */
            this["timezone"] = "";
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["updatedAt"] = null;
        }
        if (!("ssh" in $$source)) {
            /**
             * SSH 隧道配置（可选） — 零值 (Enabled=false) 表示直连数据库
             * @member
             * @type {SSHConfig}
             */
            this["ssh"] = (new SSHConfig());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Connection instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Connection}
     */
    static createFrom($$source = {}) {
        const $$createField11_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ssh" in $$parsedSource) {
            $$parsedSource["ssh"] = $$createField11_0($$parsedSource["ssh"]);
        }
        return new Connection(/** @type {Partial<Connection>} */($$parsedSource));
    }
}

/**
 * ConnectionGroup 表示连接分组（文件夹式管理）。
 */
export class ConnectionGroup {
    /**
     * Creates a new ConnectionGroup instance.
     * @param {Partial<ConnectionGroup>} [$$source = {}] - The source object to create the ConnectionGroup.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("parentId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["parentId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectionGroup instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConnectionGroup}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConnectionGroup(/** @type {Partial<ConnectionGroup>} */($$parsedSource));
    }
}

/**
 * CreateConnectionParams 是创建连接时的请求参数。
 */
export class CreateConnectionParams {
    /**
     * Creates a new CreateConnectionParams instance.
     * @param {Partial<CreateConnectionParams>} [$$source = {}] - The source object to create the CreateConnectionParams.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("groupId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["groupId"] = "";
        }
        if (!("host" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["username"] = "";
        }
        if (!("password" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["password"] = "";
        }
        if (!("database" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["database"] = "";
        }
        if (!("timezone" in $$source)) {
            /**
             * IANA 时区名（如 "Asia/Shanghai"），空值等价于 "Local"
             * @member
             * @type {string}
             */
            this["timezone"] = "";
        }
        if (!("ssh" in $$source)) {
            /**
             * SSH 隧道配置（可选）
             * @member
             * @type {SSHConfig}
             */
            this["ssh"] = (new SSHConfig());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateConnectionParams instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CreateConnectionParams}
     */
    static createFrom($$source = {}) {
        const $$createField8_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ssh" in $$parsedSource) {
            $$parsedSource["ssh"] = $$createField8_0($$parsedSource["ssh"]);
        }
        return new CreateConnectionParams(/** @type {Partial<CreateConnectionParams>} */($$parsedSource));
    }
}

/**
 * CreateDatabaseParams 是创建新数据库的请求参数。
 */
export class CreateDatabaseParams {
    /**
     * Creates a new CreateDatabaseParams instance.
     * @param {Partial<CreateDatabaseParams>} [$$source = {}] - The source object to create the CreateDatabaseParams.
     */
    constructor($$source = {}) {
        if (!("connectionId" in $$source)) {
            /**
             * 连接ID
             * @member
             * @type {string}
             */
            this["connectionId"] = "";
        }
        if (!("databaseName" in $$source)) {
            /**
             * 新数据库名
             * @member
             * @type {string}
             */
            this["databaseName"] = "";
        }
        if (!("charset" in $$source)) {
            /**
             * 字符集（如 "utf8mb4"），空表示使用 MySQL 默认值
             * @member
             * @type {string}
             */
            this["charset"] = "";
        }
        if (!("collation" in $$source)) {
            /**
             * 排序规则（如 "utf8mb4_unicode_ci"），空表示使用 MySQL 默认值
             * @member
             * @type {string}
             */
            this["collation"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateDatabaseParams instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CreateDatabaseParams}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CreateDatabaseParams(/** @type {Partial<CreateDatabaseParams>} */($$parsedSource));
    }
}

/**
 * CreateGroupParams 是创建分组时的请求参数。
 */
export class CreateGroupParams {
    /**
     * Creates a new CreateGroupParams instance.
     * @param {Partial<CreateGroupParams>} [$$source = {}] - The source object to create the CreateGroupParams.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("parentId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["parentId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateGroupParams instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CreateGroupParams}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CreateGroupParams(/** @type {Partial<CreateGroupParams>} */($$parsedSource));
    }
}

/**
 * CreateTableParams 是创建新表的请求参数。
 */
export class CreateTableParams {
    /**
     * Creates a new CreateTableParams instance.
     * @param {Partial<CreateTableParams>} [$$source = {}] - The source object to create the CreateTableParams.
     */
    constructor($$source = {}) {
        if (!("connectionId" in $$source)) {
            /**
             * 连接ID
             * @member
             * @type {string}
             */
            this["connectionId"] = "";
        }
        if (!("databaseName" in $$source)) {
            /**
             * 目标数据库名
             * @member
             * @type {string}
             */
            this["databaseName"] = "";
        }
        if (!("tableName" in $$source)) {
            /**
             * 新表名
             * @member
             * @type {string}
             */
            this["tableName"] = "";
        }
        if (!("charset" in $$source)) {
            /**
             * 字符集
             * @member
             * @type {string}
             */
            this["charset"] = "";
        }
        if (!("collation" in $$source)) {
            /**
             * 排序规则
             * @member
             * @type {string}
             */
            this["collation"] = "";
        }
        if (!("comment" in $$source)) {
            /**
             * 表注释
             * @member
             * @type {string}
             */
            this["comment"] = "";
        }
        if (!("columns" in $$source)) {
            /**
             * 列定义
             * @member
             * @type {ColumnDef[]}
             */
            this["columns"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateTableParams instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CreateTableParams}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField6_0($$parsedSource["columns"]);
        }
        return new CreateTableParams(/** @type {Partial<CreateTableParams>} */($$parsedSource));
    }
}

/**
 * DBSchemaForCompletion 是用于 SQL 自动补全的数据库 schema 快照。
 * Tables 仅包含 BASE TABLE 及其列名列表，Views 单独保存视图名列表。
 */
export class DBSchemaForCompletion {
    /**
     * Creates a new DBSchemaForCompletion instance.
     * @param {Partial<DBSchemaForCompletion>} [$$source = {}] - The source object to create the DBSchemaForCompletion.
     */
    constructor($$source = {}) {
        if (!("tables" in $$source)) {
            /**
             * 表名 → 列名列表
             * @member
             * @type {{ [_ in string]?: string[] }}
             */
            this["tables"] = {};
        }
        if (!("views" in $$source)) {
            /**
             * 视图名列表
             * @member
             * @type {string[]}
             */
            this["views"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DBSchemaForCompletion instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DBSchemaForCompletion}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType4;
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tables" in $$parsedSource) {
            $$parsedSource["tables"] = $$createField0_0($$parsedSource["tables"]);
        }
        if ("views" in $$parsedSource) {
            $$parsedSource["views"] = $$createField1_0($$parsedSource["views"]);
        }
        return new DBSchemaForCompletion(/** @type {Partial<DBSchemaForCompletion>} */($$parsedSource));
    }
}

/**
 * DDLResult 是 DDL 操作的通用返回结果。
 */
export class DDLResult {
    /**
     * Creates a new DDLResult instance.
     * @param {Partial<DDLResult>} [$$source = {}] - The source object to create the DDLResult.
     */
    constructor($$source = {}) {
        if (!("sql" in $$source)) {
            /**
             * 执行的 SQL
             * @member
             * @type {string}
             */
            this["sql"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * 操作结果消息
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DDLResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DDLResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DDLResult(/** @type {Partial<DDLResult>} */($$parsedSource));
    }
}

/**
 * FilterGroup 表示一个可嵌套的布尔筛选表达式。
 * 若 Conditions 非空，则为 AND/OR 组合节点；否则为叶子节点（使用 Column/Operator/Value）。
 */
export class FilterGroup {
    /**
     * Creates a new FilterGroup instance.
     * @param {Partial<FilterGroup>} [$$source = {}] - The source object to create the FilterGroup.
     */
    constructor($$source = {}) {
        if (!("logic" in $$source)) {
            /**
             * 组合逻辑：AND 或 OR
             * @member
             * @type {LogicOp}
             */
            this["logic"] = LogicOp.$zero;
        }
        if (!("conditions" in $$source)) {
            /**
             * 嵌套子组（至少 2 个）
             * @member
             * @type {(FilterGroup | null)[]}
             */
            this["conditions"] = [];
        }
        if (!("column" in $$source)) {
            /**
             * 叶子节点：列名
             * @member
             * @type {string}
             */
            this["column"] = "";
        }
        if (!("operator" in $$source)) {
            /**
             * 叶子节点：操作符
             * @member
             * @type {FilterOperator}
             */
            this["operator"] = FilterOperator.$zero;
        }
        if (!("value" in $$source)) {
            /**
             * 叶子节点：筛选值
             * @member
             * @type {string}
             */
            this["value"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FilterGroup instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FilterGroup}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("conditions" in $$parsedSource) {
            $$parsedSource["conditions"] = $$createField1_0($$parsedSource["conditions"]);
        }
        return new FilterGroup(/** @type {Partial<FilterGroup>} */($$parsedSource));
    }
}

/**
 * FilterOperator 表示筛选操作符。
 * @readonly
 * @enum {string}
 */
export const FilterOperator = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    OpEQ: "eq",
    OpNEQ: "neq",
    OpContains: "contains",
    OpGT: "gt",
    OpLT: "lt",
    OpIsNull: "isnull",
    OpNotNull: "notnull",
};

/**
 * ForeignKey 表示一个外键约束关系，来自 INFORMATION_SCHEMA.KEY_COLUMN_USAGE。
 * SourceTable/SourceColumn 是外键所在的源表/列，TargetTable/TargetColumn 是被引用的目标表/列。
 */
export class ForeignKey {
    /**
     * Creates a new ForeignKey instance.
     * @param {Partial<ForeignKey>} [$$source = {}] - The source object to create the ForeignKey.
     */
    constructor($$source = {}) {
        if (!("sourceTable" in $$source)) {
            /**
             * 外键源表名
             * @member
             * @type {string}
             */
            this["sourceTable"] = "";
        }
        if (!("sourceColumn" in $$source)) {
            /**
             * 外键源列名
             * @member
             * @type {string}
             */
            this["sourceColumn"] = "";
        }
        if (!("targetTable" in $$source)) {
            /**
             * 被引用的目标表名
             * @member
             * @type {string}
             */
            this["targetTable"] = "";
        }
        if (!("targetColumn" in $$source)) {
            /**
             * 被引用的目标列名
             * @member
             * @type {string}
             */
            this["targetColumn"] = "";
        }
        if (!("constraintName" in $$source)) {
            /**
             * 约束名
             * @member
             * @type {string}
             */
            this["constraintName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ForeignKey instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ForeignKey}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ForeignKey(/** @type {Partial<ForeignKey>} */($$parsedSource));
    }
}

/**
 * LogicOp 表示筛选组内的布尔连接词。
 * @readonly
 * @enum {string}
 */
export const LogicOp = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    LogicAND: "AND",
    LogicOR: "OR",
};

/**
 * PageResult 是一次分页查询的返回结果。
 */
export class PageResult {
    /**
     * Creates a new PageResult instance.
     * @param {Partial<PageResult>} [$$source = {}] - The source object to create the PageResult.
     */
    constructor($$source = {}) {
        if (!("columns" in $$source)) {
            /**
             * 列元数据
             * @member
             * @type {ColumnInfo[]}
             */
            this["columns"] = [];
        }
        if (!("rows" in $$source)) {
            /**
             * 当前页数据行
             * @member
             * @type {{ [_ in string]?: any }[]}
             */
            this["rows"] = [];
        }
        if (!("total" in $$source)) {
            /**
             * 符合条件的总行数
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("page" in $$source)) {
            /**
             * 当前页码
             * @member
             * @type {number}
             */
            this["page"] = 0;
        }
        if (!("pageSize" in $$source)) {
            /**
             * 每页条数
             * @member
             * @type {number}
             */
            this["pageSize"] = 0;
        }
        if (!("totalPages" in $$source)) {
            /**
             * 总页数
             * @member
             * @type {number}
             */
            this["totalPages"] = 0;
        }
        if (!("message" in $$source)) {
            /**
             * 状态消息
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("messageType" in $$source)) {
            /**
             * 消息类型
             * @member
             * @type {ResultType}
             */
            this["messageType"] = ResultType.$zero;
        }
        if (!("duration" in $$source)) {
            /**
             * 执行耗时（毫秒）
             * @member
             * @type {number}
             */
            this["duration"] = 0;
        }
        if (!("sql" in $$source)) {
            /**
             * 执行的 SELECT 语句（用于审计）
             * @member
             * @type {string}
             */
            this["sql"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PageResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PageResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType9;
        const $$createField1_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField0_0($$parsedSource["columns"]);
        }
        if ("rows" in $$parsedSource) {
            $$parsedSource["rows"] = $$createField1_0($$parsedSource["rows"]);
        }
        return new PageResult(/** @type {Partial<PageResult>} */($$parsedSource));
    }
}

export class QueryHistoryEntry {
    /**
     * Creates a new QueryHistoryEntry instance.
     * @param {Partial<QueryHistoryEntry>} [$$source = {}] - The source object to create the QueryHistoryEntry.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("connectionId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["connectionId"] = "";
        }
        if (!("database" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["database"] = "";
        }
        if (!("sql" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sql"] = "";
        }
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["timestamp"] = 0;
        }
        if (!("duration" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["duration"] = 0;
        }
        if (!("rowCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["rowCount"] = 0;
        }
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueryHistoryEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {QueryHistoryEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QueryHistoryEntry(/** @type {Partial<QueryHistoryEntry>} */($$parsedSource));
    }
}

/**
 * QueryResult 是一次 SQL 查询的执行结果。
 */
export class QueryResult {
    /**
     * Creates a new QueryResult instance.
     * @param {Partial<QueryResult>} [$$source = {}] - The source object to create the QueryResult.
     */
    constructor($$source = {}) {
        if (!("columns" in $$source)) {
            /**
             * 列元数据（仅 SELECT 类查询有值）
             * @member
             * @type {ColumnInfo[]}
             */
            this["columns"] = [];
        }
        if (!("rows" in $$source)) {
            /**
             * 数据行（仅 SELECT 类查询有值）
             * @member
             * @type {{ [_ in string]?: any }[]}
             */
            this["rows"] = [];
        }
        if (!("affectedRows" in $$source)) {
            /**
             * 影响行数（INSERT/UPDATE/DELETE 等）
             * @member
             * @type {number}
             */
            this["affectedRows"] = 0;
        }
        if (!("message" in $$source)) {
            /**
             * 执行状态消息，如 "3 rows affected"
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("messageType" in $$source)) {
            /**
             * 消息类型：success / error / info
             * @member
             * @type {ResultType}
             */
            this["messageType"] = ResultType.$zero;
        }
        if (!("duration" in $$source)) {
            /**
             * 执行耗时（毫秒）
             * @member
             * @type {number}
             */
            this["duration"] = 0;
        }
        if (!("queryId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["queryId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueryResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {QueryResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType9;
        const $$createField1_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField0_0($$parsedSource["columns"]);
        }
        if ("rows" in $$parsedSource) {
            $$parsedSource["rows"] = $$createField1_0($$parsedSource["rows"]);
        }
        return new QueryResult(/** @type {Partial<QueryResult>} */($$parsedSource));
    }
}

/**
 * ResultType 表示查询结果消息的类型。
 * @readonly
 * @enum {string}
 */
export const ResultType = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    ResultSuccess: "success",
    ResultError: "error",
    ResultInfo: "info",
};

/**
 * SSHConfig 表示 SSH 隧道连接参数。
 * 当 Enabled=true 时，所有数据库连接通过 SSH 隧道转发。
 * 支持密码和私钥两种认证方式，私钥优先。
 */
export class SSHConfig {
    /**
     * Creates a new SSHConfig instance.
     * @param {Partial<SSHConfig>} [$$source = {}] - The source object to create the SSHConfig.
     */
    constructor($$source = {}) {
        if (!("enabled" in $$source)) {
            /**
             * 是否启用 SSH 隧道
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("host" in $$source)) {
            /**
             * SSH 服务器地址
             * @member
             * @type {string}
             */
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * SSH 端口（默认 22）
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("user" in $$source)) {
            /**
             * SSH 登录用户名
             * @member
             * @type {string}
             */
            this["user"] = "";
        }
        if (!("password" in $$source)) {
            /**
             * SSH 密码（与私钥二选一）
             * @member
             * @type {string}
             */
            this["password"] = "";
        }
        if (!("privateKeyPath" in $$source)) {
            /**
             * 私钥文件路径（如 ~/.ssh/id_rsa）
             * @member
             * @type {string}
             */
            this["privateKeyPath"] = "";
        }
        if (!("privateKeyPass" in $$source)) {
            /**
             * 私钥口令（加密私钥时需要）
             * @member
             * @type {string}
             */
            this["privateKeyPass"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SSHConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SSHConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SSHConfig(/** @type {Partial<SSHConfig>} */($$parsedSource));
    }
}

/**
 * SortOrder 表示排序方向。
 * @readonly
 * @enum {string}
 */
export const SortOrder = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    SortASC: "ASC",
    SortDESC: "DESC",
};

/**
 * TabState 表示一个持久化的查询标签页状态，用于应用重启后恢复标签。
 */
export class TabState {
    /**
     * Creates a new TabState instance.
     * @param {Partial<TabState>} [$$source = {}] - The source object to create the TabState.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * 标签唯一标识
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * 标签标题
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("connectionId" in $$source)) {
            /**
             * 关联的连接ID
             * @member
             * @type {string}
             */
            this["connectionId"] = "";
        }
        if (!("database" in $$source)) {
            /**
             * 当前选中的数据库
             * @member
             * @type {string}
             */
            this["database"] = "";
        }
        if (!("sql" in $$source)) {
            /**
             * 编辑器中的 SQL 文本
             * @member
             * @type {string}
             */
            this["sql"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TabState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TabState}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TabState(/** @type {Partial<TabState>} */($$parsedSource));
    }
}

/**
 * TableDataParams 是 GetTableData 的入参，包含分页、排序和筛选条件。
 */
export class TableDataParams {
    /**
     * Creates a new TableDataParams instance.
     * @param {Partial<TableDataParams>} [$$source = {}] - The source object to create the TableDataParams.
     */
    constructor($$source = {}) {
        if (!("connectionId" in $$source)) {
            /**
             * 连接ID
             * @member
             * @type {string}
             */
            this["connectionId"] = "";
        }
        if (!("database" in $$source)) {
            /**
             * 数据库名
             * @member
             * @type {string}
             */
            this["database"] = "";
        }
        if (!("table" in $$source)) {
            /**
             * 表名
             * @member
             * @type {string}
             */
            this["table"] = "";
        }
        if (!("page" in $$source)) {
            /**
             * 页码，从1开始
             * @member
             * @type {number}
             */
            this["page"] = 0;
        }
        if (!("pageSize" in $$source)) {
            /**
             * 每页条数
             * @member
             * @type {number}
             */
            this["pageSize"] = 0;
        }
        if (!("sortColumn" in $$source)) {
            /**
             * 排序列名，空表示不排序
             * @member
             * @type {string}
             */
            this["sortColumn"] = "";
        }
        if (!("sortOrder" in $$source)) {
            /**
             * 排序方向
             * @member
             * @type {SortOrder}
             */
            this["sortOrder"] = SortOrder.$zero;
        }
        if (!("filters" in $$source)) {
            /**
             * 筛选条件（nil 表示无筛选）
             * @member
             * @type {FilterGroup | null}
             */
            this["filters"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TableDataParams instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TableDataParams}
     */
    static createFrom($$source = {}) {
        const $$createField7_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("filters" in $$parsedSource) {
            $$parsedSource["filters"] = $$createField7_0($$parsedSource["filters"]);
        }
        return new TableDataParams(/** @type {Partial<TableDataParams>} */($$parsedSource));
    }
}

/**
 * TableSchema 表示表的一列结构元数据，来自 INFORMATION_SCHEMA.COLUMNS。
 */
export class TableSchema {
    /**
     * Creates a new TableSchema instance.
     * @param {Partial<TableSchema>} [$$source = {}] - The source object to create the TableSchema.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * 列名
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("dataType" in $$source)) {
            /**
             * MySQL 数据类型，如 "varchar", "int"
             * @member
             * @type {string}
             */
            this["dataType"] = "";
        }
        if (!("isNullable" in $$source)) {
            /**
             * 是否可空
             * @member
             * @type {boolean}
             */
            this["isNullable"] = false;
        }
        if (!("columnKey" in $$source)) {
            /**
             * 键类型：PRI / UNI / MUL / ""
             * @member
             * @type {string}
             */
            this["columnKey"] = "";
        }
        if (!("defaultValue" in $$source)) {
            /**
             * 默认值（字符串表示），可为空
             * @member
             * @type {string}
             */
            this["defaultValue"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TableSchema instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TableSchema}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TableSchema(/** @type {Partial<TableSchema>} */($$parsedSource));
    }
}

/**
 * TestResult 是测试连接的结果。
 */
export class TestResult {
    /**
     * Creates a new TestResult instance.
     * @param {Partial<TestResult>} [$$source = {}] - The source object to create the TestResult.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TestResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TestResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TestResult(/** @type {Partial<TestResult>} */($$parsedSource));
    }
}

/**
 * UpdateConnectionParams 是更新连接时的请求参数。
 */
export class UpdateConnectionParams {
    /**
     * Creates a new UpdateConnectionParams instance.
     * @param {Partial<UpdateConnectionParams>} [$$source = {}] - The source object to create the UpdateConnectionParams.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("groupId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["groupId"] = "";
        }
        if (!("host" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["username"] = "";
        }
        if (!("password" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["password"] = "";
        }
        if (!("database" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["database"] = "";
        }
        if (!("timezone" in $$source)) {
            /**
             * IANA 时区名（如 "Asia/Shanghai"），空值等价于 "Local"
             * @member
             * @type {string}
             */
            this["timezone"] = "";
        }
        if (!("ssh" in $$source)) {
            /**
             * SSH 隧道配置（可选）
             * @member
             * @type {SSHConfig}
             */
            this["ssh"] = (new SSHConfig());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateConnectionParams instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpdateConnectionParams}
     */
    static createFrom($$source = {}) {
        const $$createField9_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ssh" in $$parsedSource) {
            $$parsedSource["ssh"] = $$createField9_0($$parsedSource["ssh"]);
        }
        return new UpdateConnectionParams(/** @type {Partial<UpdateConnectionParams>} */($$parsedSource));
    }
}

/**
 * UpdateGroupParams 是更新分组时的请求参数。
 */
export class UpdateGroupParams {
    /**
     * Creates a new UpdateGroupParams instance.
     * @param {Partial<UpdateGroupParams>} [$$source = {}] - The source object to create the UpdateGroupParams.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("parentId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["parentId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateGroupParams instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpdateGroupParams}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateGroupParams(/** @type {Partial<UpdateGroupParams>} */($$parsedSource));
    }
}

/**
 * UpdateRowParams 包含更新表中单行单个单元格所需的全部参数。
 * PkValues 是从主键列名到其值的映射，用于构建 WHERE 子句。
 */
export class UpdateRowParams {
    /**
     * Creates a new UpdateRowParams instance.
     * @param {Partial<UpdateRowParams>} [$$source = {}] - The source object to create the UpdateRowParams.
     */
    constructor($$source = {}) {
        if (!("connectionId" in $$source)) {
            /**
             * 连接ID
             * @member
             * @type {string}
             */
            this["connectionId"] = "";
        }
        if (!("database" in $$source)) {
            /**
             * 数据库名
             * @member
             * @type {string}
             */
            this["database"] = "";
        }
        if (!("table" in $$source)) {
            /**
             * 表名
             * @member
             * @type {string}
             */
            this["table"] = "";
        }
        if (!("pkValues" in $$source)) {
            /**
             * 主键列名 → 值
             * @member
             * @type {{ [_ in string]?: any }}
             */
            this["pkValues"] = {};
        }
        if (!("column" in $$source)) {
            /**
             * 要更新的目标列名
             * @member
             * @type {string}
             */
            this["column"] = "";
        }
        if (!("newValue" in $$source)) {
            /**
             * 新值（nil 表示 SQL NULL）
             * @member
             * @type {any}
             */
            this["newValue"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateRowParams instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpdateRowParams}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("pkValues" in $$parsedSource) {
            $$parsedSource["pkValues"] = $$createField3_0($$parsedSource["pkValues"]);
        }
        return new UpdateRowParams(/** @type {Partial<UpdateRowParams>} */($$parsedSource));
    }
}

/**
 * UpdateRowResult 报告单行更新操作的结果。
 */
export class UpdateRowResult {
    /**
     * Creates a new UpdateRowResult instance.
     * @param {Partial<UpdateRowResult>} [$$source = {}] - The source object to create the UpdateRowResult.
     */
    constructor($$source = {}) {
        if (!("affectedRows" in $$source)) {
            /**
             * 受影响行数
             * @member
             * @type {number}
             */
            this["affectedRows"] = 0;
        }
        if (!("message" in $$source)) {
            /**
             * 操作结果消息
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("sql" in $$source)) {
            /**
             * 执行的 SQL（用于审计）
             * @member
             * @type {string}
             */
            this["sql"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateRowResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpdateRowResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateRowResult(/** @type {Partial<UpdateRowResult>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = SSHConfig.createFrom;
const $$createType1 = ColumnDef.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = $Create.Map($Create.Any, $$createType3);
const $$createType5 = FilterGroup.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = ColumnInfo.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = $Create.Map($Create.Any, $Create.Any);
const $$createType11 = $Create.Array($$createType10);
