// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConnectionService 管理数据库连接的增删改查、测试和元数据浏览。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

/**
 * Create 创建一条新的数据库连接配置。
 */
export function Create(params: model$0.CreateConnectionParams): $CancellablePromise<model$0.Connection | null> {
    return $Call.ByID(1090303481, params).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CreateGroup 创建一个新的连接分组。
 */
export function CreateGroup(params: model$0.CreateGroupParams): $CancellablePromise<model$0.ConnectionGroup | null> {
    return $Call.ByID(908184912, params).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * Delete 删除一条数据库连接配置。
 */
export function Delete(id: string): $CancellablePromise<void> {
    return $Call.ByID(3805032270, id);
}

/**
 * DeleteGroup 删除一个分组及其下所有连接（连接移至未分组）、子分组移至上级。
 */
export function DeleteGroup(id: string): $CancellablePromise<void> {
    return $Call.ByID(744011105, id);
}

/**
 * GetDatabases 获取指定连接下的所有数据库列表。
 */
export function GetDatabases(connectionID: string): $CancellablePromise<string[]> {
    return $Call.ByID(995719319, connectionID).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetTables 获取指定数据库中所有表的列表。
 */
export function GetTables(connectionID: string, databaseName: string): $CancellablePromise<string[]> {
    return $Call.ByID(2108392282, connectionID, databaseName).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * List 返回所有连接配置。
 */
export function List(): $CancellablePromise<model$0.Connection[]> {
    return $Call.ByID(322307189).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * ListGroups 返回所有连接分组。
 */
export function ListGroups(): $CancellablePromise<model$0.ConnectionGroup[]> {
    return $Call.ByID(3937025149).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * TestConnection 测试数据库连接是否有效。
 */
export function TestConnection(id: string): $CancellablePromise<model$0.TestResult> {
    return $Call.ByID(1045268253, id).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * Update 更新一条已有的数据库连接配置。
 */
export function Update(params: model$0.UpdateConnectionParams): $CancellablePromise<model$0.Connection | null> {
    return $Call.ByID(4125118504, params).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * UpdateGroup 更新一个分组（名称或父分组）。
 */
export function UpdateGroup(params: model$0.UpdateGroupParams): $CancellablePromise<model$0.ConnectionGroup | null> {
    return $Call.ByID(3809535531, params).then(($result: any) => {
        return $$createType3($result);
    });
}

// Private type creation functions
const $$createType0 = model$0.Connection.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = model$0.ConnectionGroup.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = $Create.Array($$createType0);
const $$createType6 = $Create.Array($$createType2);
const $$createType7 = model$0.TestResult.createFrom;
