// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * QueryService 管理 SQL 查询执行和标签页持久化。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

/**
 * Execute 在指定连接的指定数据库上执行 SQL 语句并返回结果。
 */
export function Execute(connectionID: string, database: string, sqlStmt: string): $CancellablePromise<model$0.QueryResult | null> {
    return $Call.ByID(2913191668, connectionID, database, sqlStmt).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetTableData 执行分页查询，支持排序和筛选。
 * 列名（SortColumn、Filter.Column）通过 INFORMATION_SCHEMA 白名单校验，防止 SQL 注入。
 * 筛选值使用参数化查询（? 占位符），仅操作符通过白名单校验后拼入 SQL。
 */
export function GetTableData(params: model$0.TableDataParams): $CancellablePromise<model$0.PageResult | null> {
    return $Call.ByID(1395690629, params).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetTableSchema 返回指定表的列结构元数据。
 * 列信息来自 INFORMATION_SCHEMA.COLUMNS，用于前端展示列定义和构建列名白名单。
 */
export function GetTableSchema(connectionID: string, database: string, table: string): $CancellablePromise<model$0.TableSchema[]> {
    return $Call.ByID(2701588246, connectionID, database, table).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * LoadTabs 从持久化存储中恢复标签页状态。
 */
export function LoadTabs(): $CancellablePromise<model$0.TabState[]> {
    return $Call.ByID(3103459061).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * SaveTabs 持久化所有打开的标签页状态。
 */
export function SaveTabs(tabs: model$0.TabState[]): $CancellablePromise<void> {
    return $Call.ByID(869914976, tabs);
}

// Private type creation functions
const $$createType0 = model$0.QueryResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = model$0.PageResult.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = model$0.TableSchema.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = model$0.TabState.createFrom;
const $$createType7 = $Create.Array($$createType6);
