// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConnectionService 管理数据库连接的增删改查、测试和元数据浏览。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

/**
 * Create 创建一条新的数据库连接配置。
 */
export function Create(params: model$0.CreateConnectionParams): $CancellablePromise<model$0.Connection | null> {
    return $Call.ByID(1090303481, params).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CreateDatabase 在指定连接上创建一个新数据库。
 */
export function CreateDatabase(params: model$0.CreateDatabaseParams): $CancellablePromise<model$0.DDLResult | null> {
    return $Call.ByID(4221261972, params).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * CreateGroup 创建一个新的连接分组。
 */
export function CreateGroup(params: model$0.CreateGroupParams): $CancellablePromise<model$0.ConnectionGroup | null> {
    return $Call.ByID(908184912, params).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * CreateTable 在指定数据库中创建一个新表。
 */
export function CreateTable(params: model$0.CreateTableParams): $CancellablePromise<model$0.DDLResult | null> {
    return $Call.ByID(3509275091, params).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * Delete 删除一条数据库连接配置。
 */
export function Delete(id: string): $CancellablePromise<void> {
    return $Call.ByID(3805032270, id);
}

/**
 * DeleteGroup 删除一个分组及其下所有连接（连接移至未分组）、子分组移至上级。
 */
export function DeleteGroup(id: string): $CancellablePromise<void> {
    return $Call.ByID(744011105, id);
}

/**
 * DropDatabase 删除指定连接上的一个数据库。
 */
export function DropDatabase(connectionID: string, databaseName: string): $CancellablePromise<model$0.DDLResult | null> {
    return $Call.ByID(867714573, connectionID, databaseName).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * DropTable 删除指定数据库中的表。
 */
export function DropTable(connectionID: string, databaseName: string, tableName: string): $CancellablePromise<model$0.DDLResult | null> {
    return $Call.ByID(1021124708, connectionID, databaseName, tableName).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetCharsets 返回 MySQL 支持的字符集列表（含默认排序规则）。
 */
export function GetCharsets(connectionID: string): $CancellablePromise<model$0.CharsetInfo[]> {
    return $Call.ByID(3651190038, connectionID).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * GetCollations 返回指定字符集对应的排序规则列表。
 */
export function GetCollations(connectionID: string, charset: string): $CancellablePromise<string[]> {
    return $Call.ByID(106717655, connectionID, charset).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * GetDatabases 获取指定连接下的所有数据库列表。
 */
export function GetDatabases(connectionID: string): $CancellablePromise<string[]> {
    return $Call.ByID(995719319, connectionID).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * GetTables 获取指定数据库中所有表的列表。
 */
export function GetTables(connectionID: string, databaseName: string): $CancellablePromise<string[]> {
    return $Call.ByID(2108392282, connectionID, databaseName).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * List 返回所有连接配置。
 */
export function List(): $CancellablePromise<model$0.Connection[]> {
    return $Call.ByID(322307189).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * ListGroups 返回所有连接分组。
 */
export function ListGroups(): $CancellablePromise<model$0.ConnectionGroup[]> {
    return $Call.ByID(3937025149).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * TestConnection 测试数据库连接是否有效。
 */
export function TestConnection(id: string): $CancellablePromise<model$0.TestResult> {
    return $Call.ByID(1045268253, id).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * Update 更新一条已有的数据库连接配置。
 */
export function Update(params: model$0.UpdateConnectionParams): $CancellablePromise<model$0.Connection | null> {
    return $Call.ByID(4125118504, params).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * UpdateGroup 更新一个分组（名称或父分组）。
 */
export function UpdateGroup(params: model$0.UpdateGroupParams): $CancellablePromise<model$0.ConnectionGroup | null> {
    return $Call.ByID(3809535531, params).then(($result: any) => {
        return $$createType5($result);
    });
}

// Private type creation functions
const $$createType0 = model$0.Connection.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = model$0.DDLResult.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = model$0.ConnectionGroup.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = model$0.CharsetInfo.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $Create.Array($Create.Any);
const $$createType9 = $Create.Array($$createType0);
const $$createType10 = $Create.Array($$createType4);
const $$createType11 = model$0.TestResult.createFrom;
