// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConnectionService 管理数据库连接的增删改查、测试和元数据浏览。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

/**
 * Create 创建一条新的数据库连接配置。
 * @param {model$0.CreateConnectionParams} params
 * @returns {$CancellablePromise<model$0.Connection | null>}
 */
export function Create(params) {
    return $Call.ByID(1090303481, params).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * CreateDatabase 在指定连接上创建一个新数据库。
 * @param {model$0.CreateDatabaseParams} params
 * @returns {$CancellablePromise<model$0.DDLResult | null>}
 */
export function CreateDatabase(params) {
    return $Call.ByID(4221261972, params).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * CreateGroup 创建一个新的连接分组。
 * @param {model$0.CreateGroupParams} params
 * @returns {$CancellablePromise<model$0.ConnectionGroup | null>}
 */
export function CreateGroup(params) {
    return $Call.ByID(908184912, params).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * CreateTable 在指定数据库中创建一个新表。
 * @param {model$0.CreateTableParams} params
 * @returns {$CancellablePromise<model$0.DDLResult | null>}
 */
export function CreateTable(params) {
    return $Call.ByID(3509275091, params).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * Delete 删除一条数据库连接配置。
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function Delete(id) {
    return $Call.ByID(3805032270, id);
}

/**
 * DeleteGroup 删除一个分组及其下所有连接（连接移至未分组）、子分组移至上级。
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteGroup(id) {
    return $Call.ByID(744011105, id);
}

/**
 * DropDatabase 删除指定连接上的一个数据库。
 * @param {string} connectionID
 * @param {string} databaseName
 * @returns {$CancellablePromise<model$0.DDLResult | null>}
 */
export function DropDatabase(connectionID, databaseName) {
    return $Call.ByID(867714573, connectionID, databaseName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * DropTable 删除指定数据库中的表。
 * @param {string} connectionID
 * @param {string} databaseName
 * @param {string} tableName
 * @returns {$CancellablePromise<model$0.DDLResult | null>}
 */
export function DropTable(connectionID, databaseName, tableName) {
    return $Call.ByID(1021124708, connectionID, databaseName, tableName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetCharsets 返回 MySQL 支持的字符集列表（含默认排序规则）。
 * @param {string} connectionID
 * @returns {$CancellablePromise<model$0.CharsetInfo[]>}
 */
export function GetCharsets(connectionID) {
    return $Call.ByID(3651190038, connectionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * GetCollations 返回指定字符集对应的排序规则列表。
 * @param {string} connectionID
 * @param {string} charset
 * @returns {$CancellablePromise<string[]>}
 */
export function GetCollations(connectionID, charset) {
    return $Call.ByID(106717655, connectionID, charset).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * GetDatabases 获取指定连接下的所有数据库列表。
 * @param {string} connectionID
 * @returns {$CancellablePromise<string[]>}
 */
export function GetDatabases(connectionID) {
    return $Call.ByID(995719319, connectionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * GetTables 获取指定数据库中所有表的列表。
 * @param {string} connectionID
 * @param {string} databaseName
 * @returns {$CancellablePromise<string[]>}
 */
export function GetTables(connectionID, databaseName) {
    return $Call.ByID(2108392282, connectionID, databaseName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * List 返回所有连接配置。
 * @returns {$CancellablePromise<model$0.Connection[]>}
 */
export function List() {
    return $Call.ByID(322307189).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * ListGroups 返回所有连接分组。
 * @returns {$CancellablePromise<model$0.ConnectionGroup[]>}
 */
export function ListGroups() {
    return $Call.ByID(3937025149).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * TestConnection 测试数据库连接是否有效。
 * @param {string} id
 * @returns {$CancellablePromise<model$0.TestResult>}
 */
export function TestConnection(id) {
    return $Call.ByID(1045268253, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * Update 更新一条已有的数据库连接配置。
 * @param {model$0.UpdateConnectionParams} params
 * @returns {$CancellablePromise<model$0.Connection | null>}
 */
export function Update(params) {
    return $Call.ByID(4125118504, params).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * UpdateGroup 更新一个分组（名称或父分组）。
 * @param {model$0.UpdateGroupParams} params
 * @returns {$CancellablePromise<model$0.ConnectionGroup | null>}
 */
export function UpdateGroup(params) {
    return $Call.ByID(3809535531, params).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

// Private type creation functions
const $$createType0 = model$0.Connection.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = model$0.DDLResult.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = model$0.ConnectionGroup.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = model$0.CharsetInfo.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $Create.Array($Create.Any);
const $$createType9 = $Create.Array($$createType0);
const $$createType10 = $Create.Array($$createType4);
const $$createType11 = model$0.TestResult.createFrom;
