// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as ConnectionService from "./connectionservice.js";
import * as QueryService from "./queryservice.js";
export {
    ConnectionService,
    QueryService
};
