// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * QueryService 管理 SQL 查询执行和标签页持久化。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

/**
 * @param {string} queryID
 * @returns {$CancellablePromise<void>}
 */
export function CancelQuery(queryID) {
    return $Call.ByID(3752380053, queryID);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ClearHistory() {
    return $Call.ByID(1982290510);
}

/**
 * Execute 在指定连接的指定数据库上执行 SQL 语句并返回结果。
 * @param {string} connectionID
 * @param {string} database
 * @param {string} sqlStmt
 * @returns {$CancellablePromise<model$0.QueryResult | null>}
 */
export function Execute(connectionID, database, sqlStmt) {
    return $Call.ByID(2913191668, connectionID, database, sqlStmt).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetCreateTable 返回指定表的 CREATE TABLE 语句（SHOW CREATE TABLE 输出）。
 * @param {string} connectionID
 * @param {string} database
 * @param {string} table
 * @returns {$CancellablePromise<string>}
 */
export function GetCreateTable(connectionID, database, table) {
    return $Call.ByID(3834720565, connectionID, database, table);
}

/**
 * GetDBSchemaForCompletion 返回指定数据库的所有表和视图及其列信息，用于前端的 SQL 自动补全。
 * 内部仅查询 INFORMATION_SCHEMA，不发送任何其他 SQL。
 * @param {string} connectionID
 * @param {string} database
 * @returns {$CancellablePromise<model$0.DBSchemaForCompletion | null>}
 */
export function GetDBSchemaForCompletion(connectionID, database) {
    return $Call.ByID(3032534607, connectionID, database).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetForeignKeys 返回指定表的外键关系（包括出向和入向）。
 * 外键信息来自 INFORMATION_SCHEMA.KEY_COLUMN_USAGE，用于前端 ER 图渲染。
 * @param {string} connectionID
 * @param {string} database
 * @param {string} table
 * @returns {$CancellablePromise<model$0.ForeignKey[]>}
 */
export function GetForeignKeys(connectionID, database, table) {
    return $Call.ByID(3209283617, connectionID, database, table).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetTableData 执行分页查询，支持排序和筛选。
 * 列名（SortColumn、Filter.Column）通过 INFORMATION_SCHEMA 白名单校验，防止 SQL 注入。
 * 筛选值使用参数化查询（? 占位符），仅操作符通过白名单校验后拼入 SQL。
 * @param {model$0.TableDataParams} params
 * @returns {$CancellablePromise<model$0.PageResult | null>}
 */
export function GetTableData(params) {
    return $Call.ByID(1395690629, params).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * GetTableSchema 返回指定表的列结构元数据。
 * 列信息来自 INFORMATION_SCHEMA.COLUMNS，用于前端展示列定义和构建列名白名单。
 * @param {string} connectionID
 * @param {string} database
 * @param {string} table
 * @returns {$CancellablePromise<model$0.TableSchema[]>}
 */
export function GetTableSchema(connectionID, database, table) {
    return $Call.ByID(2701588246, connectionID, database, table).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * @returns {$CancellablePromise<model$0.QueryHistoryEntry[]>}
 */
export function LoadHistory() {
    return $Call.ByID(903163831).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * LoadTabs 从持久化存储中恢复标签页状态。
 * @returns {$CancellablePromise<model$0.TabState[]>}
 */
export function LoadTabs() {
    return $Call.ByID(3103459061).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * @param {model$0.QueryHistoryEntry[]} entries
 * @returns {$CancellablePromise<void>}
 */
export function SaveHistory(entries) {
    return $Call.ByID(1441455780, entries);
}

/**
 * SaveTabs 持久化所有打开的标签页状态。
 * @param {model$0.TabState[]} tabs
 * @returns {$CancellablePromise<void>}
 */
export function SaveTabs(tabs) {
    return $Call.ByID(869914976, tabs);
}

/**
 * UpdateRow 更新指定表中的单个单元格（一行一列）。
 * Column 和 PkValues 的键均通过 INFORMATION_SCHEMA 白名单校验，
 * 值使用参数化查询（? 占位符）防止 SQL 注入。
 * @param {model$0.UpdateRowParams} params
 * @returns {$CancellablePromise<model$0.UpdateRowResult | null>}
 */
export function UpdateRow(params) {
    return $Call.ByID(2687332596, params).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

// Private type creation functions
const $$createType0 = model$0.QueryResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = model$0.DBSchemaForCompletion.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = model$0.ForeignKey.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = model$0.PageResult.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = model$0.TableSchema.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = model$0.QueryHistoryEntry.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = model$0.TabState.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = model$0.UpdateRowResult.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
