// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

/**
 * ColumnInfo 描述查询结果中的一列元数据。
 */
export class ColumnInfo {
    /**
     * 列名
     */
    "name": string;

    /**
     * MySQL 类型字符串，如 "VARCHAR(255)", "INT"
     */
    "type": string;

    /** Creates a new ColumnInfo instance. */
    constructor($$source: Partial<ColumnInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ColumnInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ColumnInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ColumnInfo($$parsedSource as Partial<ColumnInfo>);
    }
}

/**
 * Connection 表示一个 MySQL 数据库连接配置。
 */
export class Connection {
    "id": string;
    "name": string;
    "groupId": string;
    "host": string;
    "port": number;
    "username": string;
    "password": string;
    "database": string;
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;

    /** Creates a new Connection instance. */
    constructor($$source: Partial<Connection> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("groupId" in $$source)) {
            this["groupId"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("password" in $$source)) {
            this["password"] = "";
        }
        if (!("database" in $$source)) {
            this["database"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Connection instance from a string or object.
     */
    static createFrom($$source: any = {}): Connection {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Connection($$parsedSource as Partial<Connection>);
    }
}

/**
 * ConnectionGroup 表示连接分组（文件夹式管理）。
 */
export class ConnectionGroup {
    "id": string;
    "name": string;
    "parentId": string;

    /** Creates a new ConnectionGroup instance. */
    constructor($$source: Partial<ConnectionGroup> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("parentId" in $$source)) {
            this["parentId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectionGroup instance from a string or object.
     */
    static createFrom($$source: any = {}): ConnectionGroup {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConnectionGroup($$parsedSource as Partial<ConnectionGroup>);
    }
}

/**
 * CreateConnectionParams 是创建连接时的请求参数。
 */
export class CreateConnectionParams {
    "name": string;
    "groupId": string;
    "host": string;
    "port": number;
    "username": string;
    "password": string;
    "database": string;

    /** Creates a new CreateConnectionParams instance. */
    constructor($$source: Partial<CreateConnectionParams> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("groupId" in $$source)) {
            this["groupId"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("password" in $$source)) {
            this["password"] = "";
        }
        if (!("database" in $$source)) {
            this["database"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateConnectionParams instance from a string or object.
     */
    static createFrom($$source: any = {}): CreateConnectionParams {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CreateConnectionParams($$parsedSource as Partial<CreateConnectionParams>);
    }
}

/**
 * CreateGroupParams 是创建分组时的请求参数。
 */
export class CreateGroupParams {
    "name": string;
    "parentId": string;

    /** Creates a new CreateGroupParams instance. */
    constructor($$source: Partial<CreateGroupParams> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("parentId" in $$source)) {
            this["parentId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateGroupParams instance from a string or object.
     */
    static createFrom($$source: any = {}): CreateGroupParams {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CreateGroupParams($$parsedSource as Partial<CreateGroupParams>);
    }
}

/**
 * FilterCondition 表示一个列筛选条件。
 */
export class FilterCondition {
    /**
     * 列名
     */
    "column": string;

    /**
     * 操作符
     */
    "operator": FilterOperator;

    /**
     * 筛选值（isnull/notnull 时忽略）
     */
    "value": string;

    /** Creates a new FilterCondition instance. */
    constructor($$source: Partial<FilterCondition> = {}) {
        if (!("column" in $$source)) {
            this["column"] = "";
        }
        if (!("operator" in $$source)) {
            this["operator"] = FilterOperator.$zero;
        }
        if (!("value" in $$source)) {
            this["value"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FilterCondition instance from a string or object.
     */
    static createFrom($$source: any = {}): FilterCondition {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FilterCondition($$parsedSource as Partial<FilterCondition>);
    }
}

/**
 * FilterOperator 表示筛选操作符。
 */
export enum FilterOperator {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    OpEQ = "eq",
    OpNEQ = "neq",
    OpContains = "contains",
    OpGT = "gt",
    OpLT = "lt",
    OpIsNull = "isnull",
    OpNotNull = "notnull",
};

/**
 * PageResult 是一次分页查询的返回结果。
 */
export class PageResult {
    /**
     * 列元数据
     */
    "columns": ColumnInfo[];

    /**
     * 当前页数据行
     */
    "rows": { [_ in string]?: any }[];

    /**
     * 符合条件的总行数
     */
    "total": number;

    /**
     * 当前页码
     */
    "page": number;

    /**
     * 每页条数
     */
    "pageSize": number;

    /**
     * 总页数
     */
    "totalPages": number;

    /**
     * 状态消息
     */
    "message": string;

    /**
     * 消息类型
     */
    "messageType": ResultType;

    /**
     * 执行耗时（毫秒）
     */
    "duration": number;

    /** Creates a new PageResult instance. */
    constructor($$source: Partial<PageResult> = {}) {
        if (!("columns" in $$source)) {
            this["columns"] = [];
        }
        if (!("rows" in $$source)) {
            this["rows"] = [];
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("page" in $$source)) {
            this["page"] = 0;
        }
        if (!("pageSize" in $$source)) {
            this["pageSize"] = 0;
        }
        if (!("totalPages" in $$source)) {
            this["totalPages"] = 0;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("messageType" in $$source)) {
            this["messageType"] = ResultType.$zero;
        }
        if (!("duration" in $$source)) {
            this["duration"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PageResult instance from a string or object.
     */
    static createFrom($$source: any = {}): PageResult {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField0_0($$parsedSource["columns"]);
        }
        if ("rows" in $$parsedSource) {
            $$parsedSource["rows"] = $$createField1_0($$parsedSource["rows"]);
        }
        return new PageResult($$parsedSource as Partial<PageResult>);
    }
}

/**
 * QueryResult 是一次 SQL 查询的执行结果。
 */
export class QueryResult {
    /**
     * 列元数据（仅 SELECT 类查询有值）
     */
    "columns": ColumnInfo[];

    /**
     * 数据行（仅 SELECT 类查询有值）
     */
    "rows": { [_ in string]?: any }[];

    /**
     * 影响行数（INSERT/UPDATE/DELETE 等）
     */
    "affectedRows": number;

    /**
     * 执行状态消息，如 "3 rows affected"
     */
    "message": string;

    /**
     * 消息类型：success / error / info
     */
    "messageType": ResultType;

    /**
     * 执行耗时（毫秒）
     */
    "duration": number;

    /** Creates a new QueryResult instance. */
    constructor($$source: Partial<QueryResult> = {}) {
        if (!("columns" in $$source)) {
            this["columns"] = [];
        }
        if (!("rows" in $$source)) {
            this["rows"] = [];
        }
        if (!("affectedRows" in $$source)) {
            this["affectedRows"] = 0;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("messageType" in $$source)) {
            this["messageType"] = ResultType.$zero;
        }
        if (!("duration" in $$source)) {
            this["duration"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueryResult instance from a string or object.
     */
    static createFrom($$source: any = {}): QueryResult {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField0_0($$parsedSource["columns"]);
        }
        if ("rows" in $$parsedSource) {
            $$parsedSource["rows"] = $$createField1_0($$parsedSource["rows"]);
        }
        return new QueryResult($$parsedSource as Partial<QueryResult>);
    }
}

/**
 * ResultType 表示查询结果消息的类型。
 */
export enum ResultType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ResultSuccess = "success",
    ResultError = "error",
    ResultInfo = "info",
};

/**
 * SortOrder 表示排序方向。
 */
export enum SortOrder {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SortASC = "ASC",
    SortDESC = "DESC",
};

/**
 * TabState 表示一个持久化的查询标签页状态，用于应用重启后恢复标签。
 */
export class TabState {
    /**
     * 标签唯一标识
     */
    "id": string;

    /**
     * 标签标题
     */
    "title": string;

    /**
     * 关联的连接ID
     */
    "connectionId": string;

    /**
     * 当前选中的数据库
     */
    "database": string;

    /**
     * 编辑器中的 SQL 文本
     */
    "sql": string;

    /** Creates a new TabState instance. */
    constructor($$source: Partial<TabState> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("connectionId" in $$source)) {
            this["connectionId"] = "";
        }
        if (!("database" in $$source)) {
            this["database"] = "";
        }
        if (!("sql" in $$source)) {
            this["sql"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TabState instance from a string or object.
     */
    static createFrom($$source: any = {}): TabState {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TabState($$parsedSource as Partial<TabState>);
    }
}

/**
 * TableDataParams 是 GetTableData 的入参，包含分页、排序和筛选条件。
 */
export class TableDataParams {
    /**
     * 连接ID
     */
    "connectionId": string;

    /**
     * 数据库名
     */
    "database": string;

    /**
     * 表名
     */
    "table": string;

    /**
     * 页码，从1开始
     */
    "page": number;

    /**
     * 每页条数
     */
    "pageSize": number;

    /**
     * 排序列名，空表示不排序
     */
    "sortColumn": string;

    /**
     * 排序方向
     */
    "sortOrder": SortOrder;

    /**
     * 筛选条件
     */
    "filters": FilterCondition[];

    /** Creates a new TableDataParams instance. */
    constructor($$source: Partial<TableDataParams> = {}) {
        if (!("connectionId" in $$source)) {
            this["connectionId"] = "";
        }
        if (!("database" in $$source)) {
            this["database"] = "";
        }
        if (!("table" in $$source)) {
            this["table"] = "";
        }
        if (!("page" in $$source)) {
            this["page"] = 0;
        }
        if (!("pageSize" in $$source)) {
            this["pageSize"] = 0;
        }
        if (!("sortColumn" in $$source)) {
            this["sortColumn"] = "";
        }
        if (!("sortOrder" in $$source)) {
            this["sortOrder"] = SortOrder.$zero;
        }
        if (!("filters" in $$source)) {
            this["filters"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TableDataParams instance from a string or object.
     */
    static createFrom($$source: any = {}): TableDataParams {
        const $$createField7_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("filters" in $$parsedSource) {
            $$parsedSource["filters"] = $$createField7_0($$parsedSource["filters"]);
        }
        return new TableDataParams($$parsedSource as Partial<TableDataParams>);
    }
}

/**
 * TableSchema 表示表的一列结构元数据，来自 INFORMATION_SCHEMA.COLUMNS。
 */
export class TableSchema {
    /**
     * 列名
     */
    "name": string;

    /**
     * MySQL 数据类型，如 "varchar", "int"
     */
    "dataType": string;

    /**
     * 是否可空
     */
    "isNullable": boolean;

    /**
     * 键类型：PRI / UNI / MUL / ""
     */
    "columnKey": string;

    /**
     * 默认值（字符串表示），可为空
     */
    "defaultValue": string;

    /** Creates a new TableSchema instance. */
    constructor($$source: Partial<TableSchema> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("dataType" in $$source)) {
            this["dataType"] = "";
        }
        if (!("isNullable" in $$source)) {
            this["isNullable"] = false;
        }
        if (!("columnKey" in $$source)) {
            this["columnKey"] = "";
        }
        if (!("defaultValue" in $$source)) {
            this["defaultValue"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TableSchema instance from a string or object.
     */
    static createFrom($$source: any = {}): TableSchema {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TableSchema($$parsedSource as Partial<TableSchema>);
    }
}

/**
 * TestResult 是测试连接的结果。
 */
export class TestResult {
    "success": boolean;
    "message": string;

    /** Creates a new TestResult instance. */
    constructor($$source: Partial<TestResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TestResult instance from a string or object.
     */
    static createFrom($$source: any = {}): TestResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TestResult($$parsedSource as Partial<TestResult>);
    }
}

/**
 * UpdateConnectionParams 是更新连接时的请求参数。
 */
export class UpdateConnectionParams {
    "id": string;
    "name": string;
    "groupId": string;
    "host": string;
    "port": number;
    "username": string;
    "password": string;
    "database": string;

    /** Creates a new UpdateConnectionParams instance. */
    constructor($$source: Partial<UpdateConnectionParams> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("groupId" in $$source)) {
            this["groupId"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("password" in $$source)) {
            this["password"] = "";
        }
        if (!("database" in $$source)) {
            this["database"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateConnectionParams instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateConnectionParams {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateConnectionParams($$parsedSource as Partial<UpdateConnectionParams>);
    }
}

/**
 * UpdateGroupParams 是更新分组时的请求参数。
 */
export class UpdateGroupParams {
    "id": string;
    "name": string;
    "parentId": string;

    /** Creates a new UpdateGroupParams instance. */
    constructor($$source: Partial<UpdateGroupParams> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("parentId" in $$source)) {
            this["parentId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateGroupParams instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateGroupParams {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateGroupParams($$parsedSource as Partial<UpdateGroupParams>);
    }
}

/**
 * UpdateRowParams 包含更新表中单行单个单元格所需的全部参数。
 * PkValues 是从主键列名到其值的映射，用于构建 WHERE 子句。
 */
export class UpdateRowParams {
    /**
     * 连接ID
     */
    "connectionId": string;

    /**
     * 数据库名
     */
    "database": string;

    /**
     * 表名
     */
    "table": string;

    /**
     * 主键列名 → 值
     */
    "pkValues": { [_ in string]?: any };

    /**
     * 要更新的目标列名
     */
    "column": string;

    /**
     * 新值（nil 表示 SQL NULL）
     */
    "newValue": any;

    /** Creates a new UpdateRowParams instance. */
    constructor($$source: Partial<UpdateRowParams> = {}) {
        if (!("connectionId" in $$source)) {
            this["connectionId"] = "";
        }
        if (!("database" in $$source)) {
            this["database"] = "";
        }
        if (!("table" in $$source)) {
            this["table"] = "";
        }
        if (!("pkValues" in $$source)) {
            this["pkValues"] = {};
        }
        if (!("column" in $$source)) {
            this["column"] = "";
        }
        if (!("newValue" in $$source)) {
            this["newValue"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateRowParams instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateRowParams {
        const $$createField3_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("pkValues" in $$parsedSource) {
            $$parsedSource["pkValues"] = $$createField3_0($$parsedSource["pkValues"]);
        }
        return new UpdateRowParams($$parsedSource as Partial<UpdateRowParams>);
    }
}

/**
 * UpdateRowResult 报告单行更新操作的结果。
 */
export class UpdateRowResult {
    /**
     * 受影响行数
     */
    "affectedRows": number;

    /**
     * 操作结果消息
     */
    "message": string;

    /**
     * 执行的 SQL（用于审计）
     */
    "sql": string;

    /** Creates a new UpdateRowResult instance. */
    constructor($$source: Partial<UpdateRowResult> = {}) {
        if (!("affectedRows" in $$source)) {
            this["affectedRows"] = 0;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("sql" in $$source)) {
            this["sql"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateRowResult instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateRowResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateRowResult($$parsedSource as Partial<UpdateRowResult>);
    }
}

// Private type creation functions
const $$createType0 = ColumnInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = FilterCondition.createFrom;
const $$createType5 = $Create.Array($$createType4);
